# Generated by Django 4.2 on 2023-06-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
